platform :ios, '7.0'
pod 'AFNetworking', '~> 2.4.1'
pod 'MWPhotoBrowser'
pod 'SVProgressHUD'
pod 'Qiniu'
pod 'IQKeyboardManager'
pod 'MOBFoundation'
pod 'SMSSDK'
=begin
pod 'ShareSDK3'
pod 'AMap2DMap'  2D地图SDK
pod 'AMapSearch'
pod 'FDStackView', '1.0'
pod 'JSCustomBadge', '~> 1.0.1'
pod 'SMVerticalSegmentedControl'
pod 'EMVerticalSegmentedControl'
pod 'ZYQAssetPickerController', '~> 1.0.0'
pod 'ZBarSDK', '~> 1.3.1'
pod 'JBChartView', '~> 2.8.10'
=end
