platform :ios, '7.0'
pod 'JBChartView', '~> 2.8.10'
pod 'AFNetworking', '~> 2.4.1'
pod 'AMap2DMap'  #2D地图SDK
pod 'AMapSearch'
pod 'JSCustomBadge', '~> 1.0.1'
pod 'SVProgressHUD'
pod 'SMVerticalSegmentedControl'
pod 'EMVerticalSegmentedControl'
pod 'ZYQAssetPickerController', '~> 1.0.0'
pod 'ZBarSDK', '~> 1.3.1'
